info:
  contact: {}
paths:
  /:
    get:
      description: get string
      operationId: get-string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Get hello
swagger: "2.0"
