basePath: /
definitions:
  models.Hackathon:
    properties:
      createdAt:
        type: string
      createdBy:
        $ref: '#/definitions/models.User'
      deletedAt:
        type: string
      description:
        type: string
      endDate:
        type: string
      id:
        type: integer
      location:
        type: string
      maxParticipants:
        type: integer
      name:
        type: string
      startDate:
        type: string
      teams:
        items:
          $ref: '#/definitions/models.Team'
        type: array
      updatedAt:
        type: string
    type: object
  models.HackathonCreate:
    properties:
      description:
        example: Un événement pour les développeurs
        type: string
      location:
        example: Paris
        type: string
      maxParticipants:
        example: 100
        type: integer
      name:
        example: Hackathon de Paris
        type: string
    type: object
  models.Registration:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      status:
        type: string
      team:
        allOf:
        - $ref: '#/definitions/models.Team'
        description: Belongs to Team
      teamID:
        description: Foreign key referencing Team.ID
        type: integer
      updatedAt:
        type: string
      user:
        allOf:
        - $ref: '#/definitions/models.User'
        description: Belongs to User
      userID:
        description: Foreign key referencing User.ID
        type: integer
    type: object
  models.Team:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      name:
        type: string
      registrations:
        description: Has many Registrations
        items:
          $ref: '#/definitions/models.Registration'
        type: array
      updatedAt:
        type: string
      users:
        description: Has many Users
        items:
          $ref: '#/definitions/models.User'
        type: array
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      password:
        type: string
      roles:
        description: 0 = user, 2 = organizer, 4 = admin
        type: integer
      team:
        allOf:
        - $ref: '#/definitions/models.Team'
        description: Belongs to Team
      teamID:
        description: Foreign key referencing Team.ID
        type: integer
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Swagger API for the Kiwi Collective project.
  title: Kiwi Collective API
  version: "1.0"
paths:
  /hackathons:
    get:
      description: Récupère une liste de tous les hackathons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hackathon'
            type: array
      summary: Lire tous les hackathons
      tags:
      - hackathons
    post:
      consumes:
      - application/json
      description: Ajoute un nouveau hackathon à la base de données
      parameters:
      - description: Hackathon à créer
        in: body
        name: hackathon
        required: true
        schema:
          $ref: '#/definitions/models.HackathonCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Hackathon'
      summary: Créer un hackathon
      tags:
      - hackathons
  /hackathons/{id}:
    delete:
      description: Supprime un hackathon par son ID
      parameters:
      - description: ID du Hackathon
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: true si la suppression est réussie
          schema:
            type: boolean
      summary: Supprimer un hackathon
      tags:
      - hackathons
    get:
      description: Récupère un hackathon par son ID
      parameters:
      - description: ID du Hackathon
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Hackathon'
      summary: Lire un hackathon spécifique
      tags:
      - hackathons
    put:
      consumes:
      - application/json
      description: Met à jour les informations d'un hackathon par son ID
      parameters:
      - description: ID du Hackathon
        in: path
        name: id
        required: true
        type: integer
      - description: Informations du Hackathon à mettre à jour
        in: body
        name: hackathon
        required: true
        schema:
          $ref: '#/definitions/models.Hackathon'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Hackathon'
      summary: Mettre à jour un hackathon
      tags:
      - hackathons
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a file to Google Cloud Storage
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: File uploaded successfully
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Upload a file
      tags:
      - files
swagger: "2.0"
