// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDhPka_-BagxL5qDjDp_XXBeWPkrl-xk',
    appId: '1:478440763767:web:49fff81f686b2d9f0cb172',
    messagingSenderId: '478440763767',
    projectId: 'kiwicollective-50cc9',
    authDomain: 'kiwicollective-50cc9.firebaseapp.com',
    databaseURL: 'https://kiwicollective-50cc9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiwicollective-50cc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijFZoweRA-UF5ReKbuQVyOHa2QaiCUmM',
    appId: '1:478440763767:android:9a7e85f3f003dcaf0cb172',
    messagingSenderId: '478440763767',
    projectId: 'kiwicollective-50cc9',
    databaseURL: 'https://kiwicollective-50cc9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiwicollective-50cc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk7-PLf0b4b6iwwwnI0lTSny-YN8FEXJc',
    appId: '1:478440763767:ios:0f2112ed6b49e8080cb172',
    messagingSenderId: '478440763767',
    projectId: 'kiwicollective-50cc9',
    databaseURL: 'https://kiwicollective-50cc9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiwicollective-50cc9.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk7-PLf0b4b6iwwwnI0lTSny-YN8FEXJc',
    appId: '1:478440763767:ios:0f2112ed6b49e8080cb172',
    messagingSenderId: '478440763767',
    projectId: 'kiwicollective-50cc9',
    databaseURL: 'https://kiwicollective-50cc9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiwicollective-50cc9.appspot.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDDhPka_-BagxL5qDjDp_XXBeWPkrl-xk',
    appId: '1:478440763767:web:25975b801af8f1f70cb172',
    messagingSenderId: '478440763767',
    projectId: 'kiwicollective-50cc9',
    authDomain: 'kiwicollective-50cc9.firebaseapp.com',
    databaseURL: 'https://kiwicollective-50cc9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kiwicollective-50cc9.appspot.com',
  );

}