name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set working directory
      run: cd back

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.22.1'

    - name: Get dependencies
      run: |
        go mod download
        go mod verify
      working-directory: ./back

    - name: Lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.57
        working-directory: ./back

    - name: Test
      run: go test -v -cover ./...
      working-directory: ./back

    - name: Build
      run: go build -v ./...
      working-directory: ./back
