name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: '1.22.1'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -v ./...
